services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "./run_django.sh;python manage.py runserver 0.0.0.0:8000" 
    depends_on:
      - db
      - cache
    env_file:
      - .env

  cache:
    image: redis
    container_name: cache 
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  db:
    image: postgres
    container_name: db 
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
        - data:/var/lib/postgresql/data

volumes:
  data:
